theme = "slick"

[icons]
name = "awesome"
[icons.overrides]
bat_charging = "  "
bat_discharging = "  "
bat_empty = "  "
bat_full = "  "
bat_half = "  "
bat_no_available = "  "
bat_quarter = "  "
bat_three_quarters = "  "

[[block]]
block = "disk_space"
format = "{icon} {available}"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "networkmanager"
interface_name_include = ["enp2s0"]

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "memory"
clickable = false
display_type = "memory"
format_mem = "{mem_used_percents}"

[[block]]
block = "time"
interval = 1
format = "%m-%d %H:%M"

